let falknerGSC = document.querySelector ("#falkner1");
let bugsyGSC = document.querySelector ("#bugsy1");
let whitneyGSC = document.querySelector ("#whitney1");
let mortyGSC = document.querySelector ("#morty1");
let chuckGSC = document.querySelector ("#chuck1");
let jasmineGSC = document.querySelector ("#jasmine1");
let pryceGSC = document.querySelector ("#pryce1");
let clairGSC = document.querySelector ("#clair1");
let willGSC = document.querySelector ("#will1");
let kogaGSC = document.querySelector ("#koga3");
let brunoGSC = document.querySelector ("#bruno3");
let karenGSC = document.querySelector ("#karen1");
let lanceGSC = document.querySelector ("#lance3");
let brockGSC = document.querySelector ("#brock3");
let mistyGSC = document.querySelector ("#misty3");
let ltsurgeGSC = document.querySelector ("#ltsurge3");
let erikaGSC = document.querySelector ("#erika3");
let janineGSC = document.querySelector ("#janine1");
let sabrinaGSC = document.querySelector ("#sabrina3");
let blaineGSC = document.querySelector ("#blaine3");
let blueGSC = document.querySelector ("#blue3");
let redGSC = document.querySelector ("#red1");

let gsc_trainers = [
    {
        namea : "Pidgey",
        levela : "LV: 7",
        typea : "Type: Normal/Flying",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Tackle",
        move2a : "-Mud-Slap",
        move3a : "",
        move4a : "",

        nameb : "Pidgeotto",
        levelb : "LV: 9",
        typeb : "Type: Normal/Flying",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Tackle",
        move2b : "-Mud-Slap",
        move3b : "-Gust",
        move4b : "",
    },

    {
        namea : "Metapod",
        levela : "LV: 14",
        typea : "Type: Bug",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Tackle",
        move2a : "-String Shot",
        move3a : "-Harden",
        move4a : "",

        nameb : "Kakuna",
        levelb : "LV: 14",
        typeb : "Type: Bug/Poison",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Poison Sting",
        move2b : "-String Shot",
        move3b : "-Harden",
        move4b : "",

        namec : "Scyther",
        levelc : "LV: 16",
        typec : "Type: Bug/Flying",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Fury Cutter",
        move2c : "-Quick Attack",
        move3c : "-Leer",
        move4c : "",
    },

    {
        namea : "Clefairy",
        levela : "LV: 18",
        typea : "Type: Normal",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Encore",
        move2a : "-Mimic",
        move3a : "-Double Slap",
        move4a : "-Metronome",

        nameb : "Miltank",
        levelb : "LV: 20",
        typeb : "Type: Normal",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Stomp",
        move2b : "-Attract",
        move3b : "-Milk Drink",
        move4b : "-Rollout",
    },

    {
        namea : "Gastly",
        levela : "LV: 21",
        typea : "Type: Ghost/Poison",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Lick",
        move2a : "-Spite",
        move3a : "-Mean Look",
        move4a : "-Curse",

        nameb : "Haunter",
        levelb : "LV: 21",
        typeb : "Type: Ghost/Poison",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Hypnosis",
        move2b : "-Curse",
        move3b : "-Mimic",
        move4b : "-Night Shade",

        namec : "Gengar",
        levelc : "LV: 25",
        typec : "Type: Ghost/Poison",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Hypnosis",
        move2c : "-Mean Look",
        move3c : "-Shadow Ball",
        move4c : "-Dream Eater",

        named : "Haunter",
        leveld : "LV: 23",
        typed : "Type: Ghost/Poison",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Spite",
        move2d : "-Mimic",
        move3d : "-Mean Look",
        move4d : "-Night Shade",
    },

    {
        namea : "Primeape",
        levela : "LV: 27",
        typea : "Type: Fighting",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Leer",
        move2a : "-Rage",
        move3a : "-Karate Chop",
        move4a : "-Fury Swipes",

        nameb : "Poliwrath",
        levelb : "LV: 30",
        typeb : "Type: Water/Fighting",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Hypnosis",
        move2b : "-Surf",
        move3b : "-Mind Reader",
        move4b : "-Dynamic Punch",
    },

    {
        namea : "Magnemite",
        levela : "LV: 30",
        typea : "Type: Electric/Steel",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Thunderbolt",
        move2a : "-Supersonic",
        move3a : "-Sonic Boom",
        move4a : "-Thunder Wave",

        nameb : "Magnemite",
        levelb : "LV: 30",
        typeb : "Type: Electric/Steel",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Thunderbolt",
        move2b : "-Supersonic",
        move3b : "-Sonic Boom",
        move4b : "-Thunder Wave",

        namec : "Steelix",
        levelc : "LV: 35",
        typec : "Type: Steel/Ground",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Iron Tail",
        move2c : "-Rock Throw",
        move3c : "-Screech",
        move4c : "-Sunny Day",
    },

    {
        namea : "Seel",
        levela : "LV: 27",
        typea : "Type: Water/Ice",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Icy Wind",
        move2a : "-Rest",
        move3a : "-Aurora Beam",
        move4a : "-Headbutt",

        nameb : "Dewgong",
        levelb : "LV: 29",
        typeb : "Type: Water/Ice",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Aurora Beam",
        move2b : "-Rest",
        move3b : "-Headbutt",
        move4b : "-Icy Wind",

        namec : "Piloswine",
        levelc : "LV: 31",
        typec : "Type: Ice/Ground",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Blizzard",
        move2c : "-Fury Attack",
        move3c : "-Mist",
        move4c : "-Icy Wind",
    },

    {
        namea : "Dragonair",
        levela : "LV: 37",
        typea : "Type: Dragon",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Surf",
        move2a : "-Dragon Breath",
        move3a : "-Slam",
        move4a : "-Thunder Wave",

        nameb : "Dragonair",
        levelb : "LV: 37",
        typeb : "Type: Dragon",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Thunderbolt",
        move2b : "-Dragon Breath",
        move3b : "-Slam",
        move4b : "-Thunder Wave",

        namec : "Dragonair",
        levelc : "LV: 37",
        typec : "Type: Dragon",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Ice Beam",
        move2c : "-Dragon Breath",
        move3c : "-Slam",
        move4c : "-Thunder Wave",

        named : "Kingdra",
        leveld : "LV: 40",
        typed : "Type: Water/Dragon",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Surf",
        move2d : "-Dragon Breath",
        move3d : "-Smokescreen",
        move4d : "-Hyper Beam",
    },

    {
        namea : "Xatu",
        levela : "LV: 40",
        typea : "Type: Psychic/Flying",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Quick Attack",
        move2a : "-Future Sight",
        move3a : "-Confuse Ray",
        move4a : "-Psychic",

        nameb : "Exeggutor",
        levelb : "LV: 41",
        typeb : "Type: Grass/Psychic",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Reflect",
        move2b : "-Egg Bomb",
        move3b : "-Psychic",
        move4b : "-Leech Seed",

        namec : "Slowbro",
        levelc : "LV: 41",
        typec : "Type: Water/Psychic",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Curse",
        move2c : "-Amnesia",
        move3c : "-Body Slam",
        move4c : "-Psychic",

        named : "Jynx",
        leveld : "LV: 41",
        typed : "Type: Ice/Psychic",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Lovely Kiss",
        move2d : "-Double Slap",
        move3d : "-Ice Punch",
        move4d : "-Psychic",

        namee : "Xatu",
        levele : "LV: 42",
        typee : "Type: Psychic/Flying",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Quick Attack",
        move2e : "-Future Sight",
        move3e : "-Confuse Ray",
        move4e : "-Psychic",
    },

    {
        namea : "Ariados",
        levela : "LV: 40",
        typea : "Type: Bug/Poison",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Spider Web",
        move2a : "-Baton Pass",
        move3a : "-Giga Drain",
        move4a : "-Double Team",

        nameb : "Venomoth",
        levelb : "LV: 41",
        typeb : "Type: Bug/Poison",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Psychic",
        move2b : "-Gust",
        move3b : "-Supersonic",
        move4b : "-Toxic",

        namec : "Forretress",
        levelc : "LV: 43",
        typec : "Type: Bug/Steel",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Protect",
        move2c : "-Swift",
        move3c : "-Spikes",
        move4c : "-Explosion",

        named : "Muk",
        leveld : "LV: 42",
        typed : "Type: Poison",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Sludge Bomb",
        move2d : "-Acid Armor",
        move3d : "-Minimize",
        move4d : "-Toxic",

        namee : "Crobat",
        levele : "LV: 44",
        typee : "Type: Poison/Flying",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Wing Attack",
        move2e : "-Quick Attack",
        move3e : "-Double Team",
        move4e : "-Toxic",
    },

    {
        namea : "Hitmontop",
        levela : "LV: 42",
        typea : "Type: Fighting",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Detect",
        move2a : "-Pursuit",
        move3a : "-Dig",
        move4a : "-Quick Attack",

        nameb : "Hitmonlee",
        levelb : "LV: 42",
        typeb : "Type: Fighting",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-High Jump Kick",
        move2b : "-Swagger",
        move3b : "-Double Kick",
        move4b : "-Foresight",

        namec : "Hitmonchan",
        levelc : "LV: 42",
        typec : "Type: Fighting",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Thunder Punch",
        move2c : "-Ice Punch",
        move3c : "-Fire Punch",
        move4c : "-Mach Punch",

        named : "Onix",
        leveld : "LV: 43",
        typed : "Type: Rock/Ground",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Sandstorm",
        move2d : "-Rock Slide",
        move3d : "-Earthquake",
        move4d : "-Bind",

        namee : "Machamp",
        levele : "LV: 46",
        typee : "Type: Fighting",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Rock Slide",
        move2e : "-Foresight",
        move3e : "-Cross Chop",
        move4e : "-Vital Throw",
    },

    {
        namea : "Umbreon",
        levela : "LV: 42",
        typea : "Type: Dark",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Feint Attack",
        move2a : "-Confuse Ray",
        move3a : "-Mean Look",
        move4a : "-Sand Attack",

        nameb : "Vileplume",
        levelb : "LV: 42",
        typeb : "Type: Grass/Poison",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Stun Spore",
        move2b : "-Acid",
        move3b : "-Petal Dance",
        move4b : "-Moonlight",

        namec : "Murkrow",
        levelc : "LV: 44",
        typec : "Type: Dark/Flying",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Feint Attack",
        move2c : "-Whirlwind",
        move3c : "-Pursuit",
        move4c : "-Quick Attack",

        named : "Gengar",
        leveld : "LV: 45",
        typed : "Type: Ghost/Poison",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Lick",
        move2d : "-Spite",
        move3d : "-Destiny Bond",
        move4d : "-Curse",

        namee : "Houndoom",
        levele : "LV: 47",
        typee : "Type: Dark/Fire",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Pursuit",
        move2e : "-Flamethrower",
        move3e : "-Crunch",
        move4e : "-Roar",
    },

    {
        namea : "Gyarados",
        levela : "LV: 44",
        typea : "Type: Water/Flying",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Rain Dance",
        move2a : "-Surf",
        move3a : "-Flail",
        move4a : "-Hyper Beam",

        nameb : "Dragonite",
        levelb : "LV: 47",
        typeb : "Type: Dragon/Flying",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Twister",
        move2b : "-Thunder Wave",
        move3b : "-Blizzard",
        move4b : "-Hyper Beam",

        namec : "Charizard",
        levelc : "LV: 46",
        typec : "Type: Fire/Flying",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Flamethrower",
        move2c : "-Wing Attack",
        move3c : "-Slash",
        move4c : "-Hyper Beam",

        named : "Aerodactyl",
        leveld : "LV: 46",
        typed : "Type: Rock/Flying",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Rock Slide",
        move2d : "-Ancient Power",
        move3d : "-Wing Attack",
        move4d : "-Hyper Beam",

        namee : "Dragonite",
        levele : "LV: 47",
        typee : "Type: Dragon/Flying",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Twister",
        move2e : "-Thunder Wave",
        move3e : "-Thunder",
        move4e : "-Hyper Beam",

        namef : "Dragonite",
        levelf : "LV: 50",
        typef : "Type: Dragon/Flying",
        abilityf: "",
        itemf : "Item: None",
        hpf : "HP: ",
        atkf : "Atk: ",
        deff : "Def: ",
        spatkf : "Sp. Atk: ",
        spdeff : "Sp. Def: ",
        spdf : "Spd: ",
        move1f : "-Outrage",
        move2f : "-Safeguard",
        move3f : "-Fire Blast",
        move4f : "-Hyper Beam",
    },

    {
        namea : "Graveler",
        levela : "LV: 41",
        typea : "Type: Rock/Ground",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Defense Curl",
        move2a : "-Rollout",
        move3a : "-Rock Slide",
        move4a : "-Earthquake",

        nameb : "Rhyhorn",
        levelb : "LV: 41",
        typeb : "Type: Ground/Rock",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Fury Attack",
        move2b : "-Scary Face",
        move3b : "-Earthquake",
        move4b : "-Horn Drill",

        namec : "Omastar",
        levelc : "LV: 42",
        typec : "Type: Rock/Water",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Bite",
        move2c : "-Surf",
        move3c : "-Spike Cannon",
        move4c : "-Protect",

        named : "Kabutops",
        leveld : "LV: 42",
        typed : "Type: Rock/Water",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Slash",
        move2d : "-Surf",
        move3d : "-Giga Drain",
        move4d : "-Endure",

        namee : "Onix",
        levele : "LV: 44",
        typee : "Type: Rock/Ground",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Sandstorm",
        move2e : "-Rock Slide",
        move3e : "-Bind",
        move4e : "-Bide",
    },

    {
        namea : "Golduck",
        levela : "LV: 42",
        typea : "Type: Water",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Surf",
        move2a : "-Disable",
        move3a : "-Psych Up",
        move4a : "-Psychic",

        nameb : "Quagsire",
        levelb : "LV: 42",
        typeb : "Type: Water/Ground",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Surf",
        move2b : "-Amnesia",
        move3b : "-Earthquake",
        move4b : "-Rain Dance",

        namec : "Lapras",
        levelc : "LV: 44",
        typec : "Type: Water/Ice",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Surf",
        move2c : "-Perish Song",
        move3c : "-Blizzard",
        move4c : "-Rain Dance",

        named : "Starmie",
        leveld : "LV: 47",
        typed : "Type: Water/Psychic",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Surf",
        move2d : "-Confuse Ray",
        move3d : "-Recover",
        move4d : "-Ice Beam",
    },

    {
        namea : "Raichu",
        levela : "LV: 44",
        typea : "Type: Electric",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Thunder Wave",
        move2a : "-Quick Attack",
        move3a : "-Thunderbolt",
        move4a : "-Thunder",

        nameb : "Electrode",
        levelb : "LV: 40",
        typeb : "Type: Electric",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Screech",
        move2b : "-Double Team",
        move3b : "-Swift",
        move4b : "-Explosion",

        namec : "Electrode",
        levelc : "LV: 40",
        typec : "Type: Electric",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Screech",
        move2c : "-Double Team",
        move3c : "-Swift",
        move4c : "-Explosion",

        named : "Magneton",
        leveld : "LV: 40",
        typed : "Type: Electric/Steel",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Zap Cannon",
        move2d : "-Double Team",
        move3d : "-Lock-On",
        move4d : "-Swift",

        namee : "Electabuzz",
        levele : "LV: 46",
        typee : "Type: Electric",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Quick Attack",
        move2e : "-Light Screen",
        move3e : "-Thunder Punch",
        move4e : "-Thunder",
    },

    {
        namea : "Tangela",
        levela : "LV: 42",
        typea : "Type: Grass",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Vine Whip",
        move2a : "-Bind",
        move3a : "-Sleep Powder",
        move4a : "-Giga Drain",

        nameb : "Victreebel",
        levelb : "LV: 46",
        typeb : "Type: Grass/Poison",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Sunny Day",
        move2b : "-Razor Leaf",
        move3b : "-Acid",
        move4b : "-Synthesis",

        namec : "Jumpluff",
        levelc : "LV: 41",
        typec : "Type: Grass/Flying",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Leech Seed",
        move2c : "-Mega Drain",
        move3c : "-Giga Drain",
        move4c : "-Cotton Spore",

        named : "Bellossom",
        leveld : "LV: 46",
        typed : "Type: Grass",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Sunny Day",
        move2d : "-Solar Beam",
        move3d : "-Synthesis",
        move4d : "-Petal Dance",
    },

    {
        namea : "Crobat",
        levela : "LV: 36",
        typea : "Type: Poison/Flying",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Wing Attack",
        move2a : "-Confuse Ray",
        move3a : "-Supersonic",
        move4a : "-Screech",

        nameb : "Weezing",
        levelb : "LV: 36",
        typeb : "Type: Poison",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Sludge Bomb",
        move2b : "-Toxic",
        move3b : "-Explosion",
        move4b : "-Smog",

        namec : "Weezing",
        levelc : "LV: 36",
        typec : "Type: Poison",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Sludge Bomb",
        move2c : "-Toxic",
        move3c : "-Explosion",
        move4c : "-Smog",

        named : "Ariados",
        leveld : "LV: 33",
        typed : "Type: Bug/Poison",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-String Shot",
        move2d : "-Night Shade",
        move3d : "-Scary Face",
        move4d : "-Giga Drain",

        namee : "Venomoth",
        levele : "LV: 39",
        typee : "Type: Bug/Poison",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Toxic",
        move2e : "-Double Team",
        move3e : "-Psychic",
        move4e : "-Supersonic",
    },

    {
        namea : "Espeon",
        levela : "LV: 46",
        typea : "Type: Psychic",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Psychic",
        move2a : "-Sand Attack",
        move3a : "-Quick Attack",
        move4a : "-Swift",

        nameb : "Mr. Mime",
        levelb : "LV: 46",
        typeb : "Type: Psychic",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Psychic",
        move2b : "-Barrier",
        move3b : "-Reflect",
        move4b : "-Baton Pass",

        namec : "Alakazam",
        levelc : "LV: 48",
        typec : "Type: Psychic",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Psychic",
        move2c : "-Reflect",
        move3c : "-Recover",
        move4c : "-Future Sight",
    },

    {
        namea : "Magcargo",
        levela : "LV: 45",
        typea : "Type: Fire/Rock",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Flamethrower",
        move2a : "-Curse",
        move3a : "-Smog",
        move4a : "-Rock Slide",

        nameb : "Magmar",
        levelb : "LV: 45",
        typeb : "Type: Fire",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Fire Punch",
        move2b : "-Confuse Ray",
        move3b : "-Thunder Punch",
        move4b : "-Sunny Day",

        namec : "Rapidash",
        levelc : "LV: 50",
        typec : "Type: Fire",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Quick Attack",
        move2c : "-Fire Spin",
        move3c : "-Fury Attack",
        move4c : "-Fire Blast",
    },

    {
        namea : "Pidgeot",
        levela : "LV: 56",
        typea : "Type: Normal/Flying",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Quick Attack",
        move2a : "-Whirlwind",
        move3a : "-Wing Attack",
        move4a : "-Mirror Move",

        nameb : "Alakazam",
        levelb : "LV: 54",
        typeb : "Type: Psychic",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Psychic",
        move2b : "-Recover",
        move3b : "-Disable",
        move4b : "-Reflect",

        namec : "Rhydon",
        levelc : "LV: 56",
        typec : "Type: Ground/Rock",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Rock Slide",
        move2c : "-Earthquake",
        move3c : "-Sandstorm",
        move4c : "-Fury Attack",

        named : "Gyarados",
        leveld : "LV: 58",
        typed : "Type: Water/Flying",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Rain Dance",
        move2d : "-Hydro Pump",
        move3d : "-Twister",
        move4d : "-Hyper Beam",

        namee : "Exeggutor",
        levele : "LV: 58",
        typee : "Type: Grass/Psychic",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Sunny Day",
        move2e : "-Solar Beam",
        move3e : "-Leech Seed",
        move4e : "-Egg Bomb",

        namef : "Arcanine",
        levelf : "LV: 58",
        typef : "Type: Fire",
        abilityf: "",
        itemf : "Item: None",
        hpf : "HP: ",
        atkf : "Atk: ",
        deff : "Def: ",
        spatkf : "Sp. Atk: ",
        spdeff : "Sp. Def: ",
        spdf : "Spd: ",
        move1f : "-Flamethrower",
        move2f : "-Swift",
        move3f : "-Extreme Speed",
        move4f : "-Roar",
    },

    {
        namea : "Pikachu",
        levela : "LV: 81",
        typea : "Type: Electric",
        abilitya: "",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Quick Attack",
        move2a : "-Thunderbolt",
        move3a : "-Thunder",
        move4a : "-Charm",

        nameb : "Espeon",
        levelb : "LV: 73",
        typeb : "Type: Psychic",
        abilityb: "",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Psychic",
        move2b : "-Reflect",
        move3b : "-Swift",
        move4b : "-Mud-Slap",

        namec : "Snorlax",
        levelc : "LV: 75",
        typec : "Type: Normal",
        abilityc: "",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Rest",
        move2c : "-Snore",
        move3c : "-Body Slam",
        move4c : "-Amnesia",

        named : "Venusaur",
        leveld : "LV: 77",
        typed : "Type: Grass/Poison",
        abilityd: "",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Giga Drain",
        move2d : "-Sunny Day",
        move3d : "-Solar Beam",
        move4d : "-Synthesis",

        namee : "Charizard",
        levele : "LV: 77",
        typee : "Type: Fire/Flying",
        abilitye: "",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Flamethrower",
        move2e : "-Fire Spin",
        move3e : "-Wing Attack",
        move4e : "-Slash",

        namef : "Blastoise",
        levelf : "LV: 77",
        typef : "Type: Water",
        abilityf: "",
        itemf : "Item: None",
        hpf : "HP: ",
        atkf : "Atk: ",
        deff : "Def: ",
        spatkf : "Sp. Atk: ",
        spdeff : "Sp. Def: ",
        spdf : "Spd: ",
        move1f : "-Surf",
        move2f : "-Blizzard",
        move3f : "-Whirlpool",
        move4f : "-Rain Dance",
    }
]

function displayGSCTrainers() {

    let newTrainerId = this.id;
    if (newTrainerId !== currentTrainerId) {
        currentTrainerId = newTrainerId;
        showGSCImages(newTrainerId);
        showPokemonGSCImages(newTrainerId);
    }


    let gscTrainer = this.dataset.member;

    document.querySelector('#name1').textContent = gsc_trainers [gscTrainer].namea;
    document.querySelector('#level1').textContent = gsc_trainers [gscTrainer].levela;
    document.querySelector('#type1').textContent = gsc_trainers [gscTrainer].typea;
    document.querySelector('#ability1').textContent= gsc_trainers [gscTrainer].abilitya;
    document.querySelector('#item1').textContent = gsc_trainers [gscTrainer].itema;
    document.querySelector('#hp1').textContent = gsc_trainers [gscTrainer].hpa;
    document.querySelector('#atk1').textContent = gsc_trainers [gscTrainer].atka;
    document.querySelector('#def1').textContent = gsc_trainers [gscTrainer].defa;
    document.querySelector('#spatk1').textContent = gsc_trainers [gscTrainer].spatka;
    document.querySelector('#spdef1').textContent = gsc_trainers [gscTrainer].spdefa;
    document.querySelector('#spd1').textContent = gsc_trainers [gscTrainer].spda;
    document.querySelector('#move1_1').textContent = gsc_trainers [gscTrainer].move1a;
    document.querySelector('#move2_1').textContent = gsc_trainers [gscTrainer].move2a;
    document.querySelector('#move3_1').textContent = gsc_trainers [gscTrainer].move3a;
    document.querySelector('#move4_1').textContent = gsc_trainers [gscTrainer].move4a;

    
    document.querySelector('#name2').textContent = gsc_trainers [gscTrainer].nameb;
    document.querySelector('#level2').textContent = gsc_trainers [gscTrainer].levelb;
    document.querySelector('#type2').textContent = gsc_trainers [gscTrainer].typeb;
    document.querySelector('#ability2').textContent= gsc_trainers [gscTrainer].abilityb;
    document.querySelector('#item2').textContent = gsc_trainers [gscTrainer].itemb;
    document.querySelector('#hp2').textContent = gsc_trainers [gscTrainer].hpb;
    document.querySelector('#atk2').textContent = gsc_trainers [gscTrainer].atkb;
    document.querySelector('#def2').textContent = gsc_trainers [gscTrainer].defb;
    document.querySelector('#spatk2').textContent = gsc_trainers [gscTrainer].spatkb;
    document.querySelector('#spdef2').textContent = gsc_trainers [gscTrainer].spdefb;
    document.querySelector('#spd2').textContent = gsc_trainers [gscTrainer].spdb;
    document.querySelector('#move1_2').textContent = gsc_trainers [gscTrainer].move1b;
    document.querySelector('#move2_2').textContent = gsc_trainers [gscTrainer].move2b;
    document.querySelector('#move3_2').textContent = gsc_trainers [gscTrainer].move3b;
    document.querySelector('#move4_2').textContent = gsc_trainers [gscTrainer].move4b;

    document.querySelector('#name3').textContent = gsc_trainers [gscTrainer].namec;
    document.querySelector('#level3').textContent = gsc_trainers [gscTrainer].levelc;
    document.querySelector('#type3').textContent = gsc_trainers [gscTrainer].typec;
    document.querySelector('#ability3').textContent= gsc_trainers [gscTrainer].abilityc;
    document.querySelector('#item3').textContent = gsc_trainers [gscTrainer].itemc;
    document.querySelector('#hp3').textContent = gsc_trainers [gscTrainer].hpc;
    document.querySelector('#atk3').textContent = gsc_trainers [gscTrainer].atkc;
    document.querySelector('#def3').textContent = gsc_trainers [gscTrainer].defc;
    document.querySelector('#spatk3').textContent = gsc_trainers [gscTrainer].spatkc;
    document.querySelector('#spdef3').textContent = gsc_trainers [gscTrainer].spdefc;
    document.querySelector('#spd3').textContent = gsc_trainers [gscTrainer].spdc;
    document.querySelector('#move1_3').textContent = gsc_trainers [gscTrainer].move1c;
    document.querySelector('#move2_3').textContent = gsc_trainers [gscTrainer].move2c;
    document.querySelector('#move3_3').textContent = gsc_trainers [gscTrainer].move3c;
    document.querySelector('#move4_3').textContent = gsc_trainers [gscTrainer].move4c;

    document.querySelector('#name4').textContent = gsc_trainers [gscTrainer].named;
    document.querySelector('#level4').textContent = gsc_trainers [gscTrainer].leveld;
    document.querySelector('#type4').textContent = gsc_trainers [gscTrainer].typed;
    document.querySelector('#ability4').textContent= gsc_trainers [gscTrainer].abilityd;
    document.querySelector('#item4').textContent = gsc_trainers [gscTrainer].itemd;
    document.querySelector('#hp4').textContent = gsc_trainers [gscTrainer].hpd;
    document.querySelector('#atk4').textContent = gsc_trainers [gscTrainer].atkd;
    document.querySelector('#def4').textContent = gsc_trainers [gscTrainer].defd;
    document.querySelector('#spatk4').textContent = gsc_trainers [gscTrainer].spatkd;
    document.querySelector('#spdef4').textContent = gsc_trainers [gscTrainer].spdefd;
    document.querySelector('#spd4').textContent = gsc_trainers [gscTrainer].spdd;
    document.querySelector('#move1_4').textContent = gsc_trainers [gscTrainer].move1d;
    document.querySelector('#move2_4').textContent = gsc_trainers [gscTrainer].move2d;
    document.querySelector('#move3_4').textContent = gsc_trainers [gscTrainer].move3d;
    document.querySelector('#move4_4').textContent = gsc_trainers [gscTrainer].move4d;

    document.querySelector('#name5').textContent = gsc_trainers [gscTrainer].namee;
    document.querySelector('#level5').textContent = gsc_trainers [gscTrainer].levele;
    document.querySelector('#type5').textContent = gsc_trainers [gscTrainer].typee;
    document.querySelector('#ability5').textContent= gsc_trainers [gscTrainer].abilitye;
    document.querySelector('#item5').textContent = gsc_trainers [gscTrainer].iteme;
    document.querySelector('#hp5').textContent = gsc_trainers [gscTrainer].hpe;
    document.querySelector('#atk5').textContent = gsc_trainers [gscTrainer].atke;
    document.querySelector('#def5').textContent = gsc_trainers [gscTrainer].defe;
    document.querySelector('#spatk5').textContent = gsc_trainers [gscTrainer].spatke;
    document.querySelector('#spdef5').textContent = gsc_trainers [gscTrainer].spdefe;
    document.querySelector('#spd5').textContent = gsc_trainers [gscTrainer].spde;
    document.querySelector('#move1_5').textContent = gsc_trainers [gscTrainer].move1e;
    document.querySelector('#move2_5').textContent = gsc_trainers [gscTrainer].move2e;
    document.querySelector('#move3_5').textContent = gsc_trainers [gscTrainer].move3e;
    document.querySelector('#move4_5').textContent = gsc_trainers [gscTrainer].move4e;

    document.querySelector('#name6').textContent = gsc_trainers [gscTrainer].namef;
    document.querySelector('#level6').textContent = gsc_trainers [gscTrainer].levelf;
    document.querySelector('#type6').textContent = gsc_trainers [gscTrainer].typef;
    document.querySelector('#ability6').textContent= gsc_trainers [gscTrainer].abilityf;
    document.querySelector('#item6').textContent = gsc_trainers [gscTrainer].itemf;
    document.querySelector('#hp6').textContent = gsc_trainers [gscTrainer].hpf;
    document.querySelector('#atk6').textContent = gsc_trainers [gscTrainer].atkf;
    document.querySelector('#def6').textContent = gsc_trainers [gscTrainer].deff;
    document.querySelector('#spatk6').textContent = gsc_trainers [gscTrainer].spatkf;
    document.querySelector('#spdef6').textContent = gsc_trainers [gscTrainer].spdeff;
    document.querySelector('#spd6').textContent = gsc_trainers [gscTrainer].spdf;
    document.querySelector('#move1_6').textContent = gsc_trainers [gscTrainer].move1f;
    document.querySelector('#move2_6').textContent = gsc_trainers [gscTrainer].move2f;
    document.querySelector('#move3_6').textContent = gsc_trainers [gscTrainer].move3f;
    document.querySelector('#move4_6').textContent = gsc_trainers [gscTrainer].move4f;
}

function showGSCImages(trainerId) {
    var trainerPicture = document.querySelector("#trainer_image");
    
    trainerPicture.innerHTML = "";

    var imgTrainer = document.createElement("img");
    imgTrainer.src = "images/trainers/gsc/" + trainerId + ".png";
    trainerPicture.appendChild(imgTrainer);
}

function showPokemonGSCImages(trainerId) {
    var pokemon1Picture = document.querySelector("#pokemon_1_image");
    var pokemon2Picture = document.querySelector("#pokemon_2_image");
    var pokemon3Picture = document.querySelector("#pokemon_3_image");
    var pokemon4Picture = document.querySelector("#pokemon_4_image");
    var pokemon5Picture = document.querySelector("#pokemon_5_image");
    var pokemon6Picture = document.querySelector("#pokemon_6_image");
    var imgPokemon1 = document.createElement("img");
    var imgPokemon2 = document.createElement("img");
    var imgPokemon3 = document.createElement("img");
    var imgPokemon4 = document.createElement("img");
    var imgPokemon5 = document.createElement("img");
    var imgPokemon6 = document.createElement("img");
    
    pokemon1Picture.innerHTML = "";
    pokemon2Picture.innerHTML = "";
    pokemon3Picture.innerHTML = "";
    pokemon4Picture.innerHTML = "";
    pokemon5Picture.innerHTML = "";
    pokemon6Picture.innerHTML = "";

    
    imgPokemon1.src = "images/pokemon/gsc/" + trainerId + "_1.png";
    imgPokemon2.src = "images/pokemon/gsc/" + trainerId + "_2.png";
    imgPokemon3.src = "images/pokemon/gsc/" + trainerId + "_3.png";
    imgPokemon4.src = "images/pokemon/gsc/" + trainerId + "_4.png";
    imgPokemon5.src = "images/pokemon/gsc/" + trainerId + "_5.png";
    imgPokemon6.src = "images/pokemon/gsc/" + trainerId + "_6.png";

    pokemon1Picture.appendChild(imgPokemon1);
    pokemon2Picture.appendChild(imgPokemon2);
    pokemon3Picture.appendChild(imgPokemon3);
    pokemon4Picture.appendChild(imgPokemon4);
    pokemon5Picture.appendChild(imgPokemon5);
    pokemon6Picture.appendChild(imgPokemon6);
}

falknerGSC.addEventListener('click', displayGSCTrainers);
bugsyGSC.addEventListener('click', displayGSCTrainers);
whitneyGSC.addEventListener('click', displayGSCTrainers);
mortyGSC.addEventListener('click', displayGSCTrainers);
chuckGSC.addEventListener('click', displayGSCTrainers);
jasmineGSC.addEventListener('click', displayGSCTrainers);
pryceGSC.addEventListener('click', displayGSCTrainers);
clairGSC.addEventListener('click', displayGSCTrainers);
willGSC.addEventListener('click', displayGSCTrainers);
kogaGSC.addEventListener('click', displayGSCTrainers);
brunoGSC.addEventListener('click', displayGSCTrainers);
karenGSC.addEventListener('click', displayGSCTrainers);
lanceGSC.addEventListener('click', displayGSCTrainers);
brockGSC.addEventListener('click', displayGSCTrainers);
mistyGSC.addEventListener('click', displayGSCTrainers);
ltsurgeGSC.addEventListener('click', displayGSCTrainers);
erikaGSC.addEventListener('click', displayGSCTrainers);
janineGSC.addEventListener('click', displayGSCTrainers);
sabrinaGSC.addEventListener('click', displayGSCTrainers);
blaineGSC.addEventListener('click', displayGSCTrainers);
blueGSC.addEventListener('click', displayGSCTrainers);
redGSC.addEventListener('click', displayGSCTrainers);