let falknerHGSS = document.querySelector ("#falkner2");
let bugsyHGSS = document.querySelector ("#bugsy2");
let whitneyHGSS = document.querySelector ("#whitney2");
let mortyHGSS = document.querySelector ("#morty2");
let chuckHGSS = document.querySelector ("#chuck2");
let jasmineHGSS = document.querySelector ("#jasmine2");
let pryceHGSS = document.querySelector ("#pryce2");
let clairHGSS = document.querySelector ("#clair2");
let willHGSS = document.querySelector ("#will2");
let kogaHGSS = document.querySelector ("#koga5");
let brunoHGSS = document.querySelector ("#bruno5");
let karenHGSS = document.querySelector ("#karen2");
let lanceHGSS = document.querySelector ("#lance5");
let brockHGSS = document.querySelector ("#brock5");
let mistyHGSS = document.querySelector ("#misty5");
let ltsurgeHGSS = document.querySelector ("#ltsurge5");
let erikaHGSS = document.querySelector ("#erika5");
let janineHGSS = document.querySelector ("#janine2");
let sabrinaHGSS = document.querySelector ("#sabrina5");
let blaineHGSS = document.querySelector ("#blaine5");
let blueHGSS = document.querySelector ("#blue5");
let redHGSS = document.querySelector ("#red2");

let hgss_trainers = [
    {
        namea : "Pidgey",
        levela : "LV: 9",
        typea : "Type: Normal/Flying",
        abilitya: "Ability: Keen Eye",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Tackle",
        move2a : "-Sand Attack",
        move3a : "-",
        move4a : "-",

        nameb : "Pidgeotto",
        levelb : "LV: 13",
        typeb : "Type: Normal/Flying",
        abilityb: "Ability: Keen Eye",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Tackle",
        move2b : "-Roost",
        move3b : "-Gust",
        move4b : "-",
    },

    {
        namea : "Scyther",
        levela : "LV: 17",
        typea : "Type: Bug/Flying",
        abilitya: "Ability: ",
        itema : "Item: Sitrus Berry",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-U-Turn",
        move2a : "-Quick Attack",
        move3a : "-Leer",
        move4a : "-Focus Energy",

        nameb : "Metapod",
        levelb : "LV: 15",
        typeb : "Type: Bug",
        abilityb: "Ability: Shed Skin",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Tackle",
        move2b : "",
        move3b : "",
        move4b : "",

        namec : "Kakuna",
        levelc : "LV: 15",
        typec : "Type: Bug/Poison",
        abilityc: "Ability: Shed Skin",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Poison Sting",
        move2c : "",
        move3c : "",
        move4c : "",
    },

    {
        namea : "Clefairy",
        levela : "LV: 17",
        typea : "Type: Normal",
        abilitya: "Ability: Cute Charm",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Encore",
        move2a : "-Mimic",
        move3a : "-Double Slap",
        move4a : "-Metronome",

        nameb : "Miltank",
        levelb : "LV: 19",
        typeb : "Type: Normal",
        abilityb: "Ability: Scrappy",
        itemb : "Item: Lum Berry",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Stomp",
        move2b : "-Attract",
        move3b : "-Milk Drink",
        move4b : "-Rollout",
    },

    {
        namea : "Gastly",
        levela : "LV: 21",
        typea : "Type: Ghost/Poison",
        abilitya: "Ability: Levitate",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Lick",
        move2a : "-Spite",
        move3a : "-Mean Look",
        move4a : "-Curse",

        nameb : "Haunter",
        levelb : "LV: 21",
        typeb : "Type: Ghost/Poison",
        abilityb: "Ability: Levitate",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Hypnosis",
        move2b : "-Curse",
        move3b : "-Dream Eater",
        move4b : "-Nightmare",

        namec : "Gengar",
        levelc : "LV: 25",
        typec : "Type: Ghost/Poison",
        abilityc: "Ability: Levitate",
        itemc : "Item: Sitrus Berry",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Hypnosis",
        move2c : "-Mean Look",
        move3c : "-Shadow Ball",
        move4c : "-Sucker Punch",

        named : "Haunter",
        leveld : "LV: 23",
        typed : "Type: Ghost/Poison",
        abilityd: "Ability: Levitate",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Curse",
        move2d : "-Sucker Punch",
        move3d : "-Mean Look",
        move4d : "-Night Shade",
    },

    {
        namea : "Primeape",
        levela : "LV: 29",
        typea : "Type: Fighting",
        abilitya: "Ability: Vital Spirit",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Leer",
        move2a : "-Double Team",
        move3a : "-Rock Slide",
        move4a : "-Focus Punch",

        nameb : "Poliwrath",
        levelb : "LV: 31",
        typeb : "Type: Water/Fighting",
        abilityb: "Ability: Water Absorb",
        itemb : "Item: Sitrus Berry",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Hypnosis",
        move2b : "-Surf",
        move3b : "-Body Slam",
        move4b : "-Focus Punch",
    },

    {
        namea : "Magnemite",
        levela : "LV: 30",
        typea : "Type: Electric/Steel",
        abilitya: "Ability: Magnet Pull",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Thunderbolt",
        move2a : "-Supersonic",
        move3a : "-Sonic Boom",
        move4a : "-Thunder Wave",

        nameb : "Magnemite",
        levelb : "LV: 30",
        typeb : "Type: Electric/Steel",
        abilityb: "Ability: Magnet Pull",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Thunderbolt",
        move2b : "-Supersonic",
        move3b : "-Sonic Boom",
        move4b : "-Thunder Wave",

        namec : "Steelix",
        levelc : "LV: 35",
        typec : "Type: Steel/Ground",
        abilityc: "Ability: Sturdy",
        itemc : "Item: ",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Iron Tail",
        move2c : "-Rock Throw",
        move3c : "-Screech",
        move4c : "-Sandstorm",
    },

    {
        namea : "Seel",
        levela : "LV: 30",
        typea : "Type: Water/Ice",
        abilitya: "Ability: Thick Fat",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Icy Wind",
        move2a : "-Rest",
        move3a : "-Snore",
        move4a : "-Hail",

        nameb : "Dewgong",
        levelb : "LV: 32",
        typeb : "Type: Water/Ice",
        abilityb: "Ability: Thick Fat",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Aurora Beam",
        move2b : "-Rest",
        move3b : "-Sleep Talk",
        move4b : "-Ice Shard",

        namec : "Piloswine",
        levelc : "LV: 34",
        typec : "Type: Ice/Ground",
        abilityc: "Ability: ",
        itemc : "Item: ",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Blizzard",
        move2c : "-Ice Fang",
        move3c : "-Mud Bomb",
        move4c : "-Hail",
    },

    {
        namea : "Gyarados",
        levela : "LV: 38",
        typea : "Type: Water/Flying",
        abilitya: "Ability: Intimidate",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Bite",
        move2a : "-Twister",
        move3a : "-Dragon Rage",
        move4a : "-Dragon Pulse",

        nameb : "Dragonair",
        levelb : "LV: 38",
        typeb : "Type: Dragon",
        abilityb: "Ability: Shed Skin",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Aqua Tail",
        move2b : "-Dragon Pulse",
        move3b : "-Slam",
        move4b : "-Thunder Wave",

        namec : "Dragonair",
        levelc : "LV: 38",
        typec : "Type: Dragon",
        abilityc: "Ability: Shed Skin",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Fire Blast",
        move2c : "-Dragon Pulse",
        move3c : "-Slam",
        move4c : "-Thunder Wave",

        named : "Kingdra",
        leveld : "LV: 41",
        typed : "Type: Water/Dragon",
        abilityd: "Ability: Sniper",
        itemd : "Item: Sitrus Berry",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Hydro Pump",
        move2d : "-Dragon Pulse",
        move3d : "-Smokescreen",
        move4d : "-Hyper Beam",
    },

    {
        namea : "Xatu",
        levela : "LV: 40",
        typea : "Type: Psychic/Flying",
        abilitya: "Ability: Synchronize",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-U-Turn",
        move2a : "-Me First",
        move3a : "-Confuse Ray",
        move4a : "-Psychic",

        nameb : "Jynx",
        levelb : "LV: 41",
        typeb : "Type: Ice/Psychic",
        abilityb: "Ability: Oblivious",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Lovely Kiss",
        move2b : "-Double Slap",
        move3b : "-Ice Punch",
        move4b : "-Psychic",

        namec : "Slowbro",
        levelc : "LV: 41",
        typec : "Type: Water/Psychic",
        abilityc: "Ability: ",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Curse",
        move2c : "-Amnesia",
        move3c : "-Water Pulse",
        move4c : "-Psychic",

        named : "Exeggutor",
        leveld : "LV: 41",
        typed : "Type: Grass/Psychic",
        abilityd: "Ability: Chlorophyll",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Hypnosis",
        move2d : "-Egg Bomb",
        move3d : "-Psychic",
        move4d : "-Reflect",

        namee : "Xatu",
        levele : "LV: 42",
        typee : "Type: Psychic/Flying",
        abilitye: "Ability: Early Bird",
        iteme : "Item: Sitrus Berry",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Aerial Ace",
        move2e : "-Ominous Wind",
        move3e : "-Confuse Ray",
        move4e : "-Psychic",
    },

    {
        namea : "Ariados",
        levela : "LV: 40",
        typea : "Type: Bug/Poison",
        abilitya: "Ability: Insomnia",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Spider Web",
        move2a : "-Baton Pass",
        move3a : "-Giga Drain",
        move4a : "-Poison Jab",

        nameb : "Forretress",
        levelb : "LV: 43",
        typeb : "Type: Bug/Steel",
        abilityb: "Ability: Sturdy",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Protect",
        move2b : "-Swift",
        move3b : "-Toxic Spikes",
        move4b : "-Explosion",

        namec : "Muk",
        levelc : "LV: 42",
        typec : "Type: Poison",
        abilityc: "Ability: Sticky Hold",
        itemc : "Item: Black Sludge",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Gunk Shot",
        move2c : "-Screech",
        move3c : "-Minimize",
        move4c : "-Toxic",

        named : "Venomoth",
        leveld : "LV: 41",
        typed : "Type: Bug/Poison",
        abilityd: "Ability: Shield Dust",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Psychic",
        move2d : "-Gust",
        move3d : "-Supersonic",
        move4d : "-Toxic",

        namee : "Crobat",
        levele : "LV: 44",
        typee : "Type: Poison/Flying",
        abilitye: "Ability: Inner Focus",
        iteme : "Item: ",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Wing Attack",
        move2e : "-Quick Attack",
        move3e : "-Double Team",
        move4e : "-Poison Fang",
    },

    {
        namea : "Hitmontop",
        levela : "LV: 42",
        typea : "Type: Fighting",
        abilitya: "Ability: Technician",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Triple Kick",
        move2a : "-Counter",
        move3a : "-Dig",
        move4a : "-Quick Attack",

        nameb : "Hitmonlee",
        levelb : "LV: 42",
        typeb : "Type: Fighting",
        abilityb: "Ability: Reckless",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-High Jump Kick",
        move2b : "-Swagger",
        move3b : "-Blaze Kick",
        move4b : "-Focus Energy",

        namec : "Hitmonchan",
        levelc : "LV: 42",
        typec : "Type: Fighting",
        abilityc: "Ability: Iron Fist",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Thunder Punch",
        move2c : "-Ice Punch",
        move3c : "-Fire Punch",
        move4c : "-Bullet Punch",

        named : "Onix",
        leveld : "LV: 43",
        typed : "Type: Rock/Ground",
        abilityd: "Ability: Sturdy",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Sandstorm",
        move2d : "-Rock Slide",
        move3d : "-Earthquake",
        move4d : "-Dragon Breath",

        namee : "Machamp",
        levele : "LV: 46",
        typee : "Type: Fighting",
        abilitye: "Ability: No Guard",
        iteme : "Item: Sitrus Berry",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Rock Slide",
        move2e : "-Foresight",
        move3e : "-Cross Chop",
        move4e : "-Revenge",
    },

    {
        namea : "Umbreon",
        levela : "LV: 42",
        typea : "Type: Dark",
        abilitya: "Ability: Synchronize",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Feint Attack",
        move2a : "-Confuse Ray",
        move3a : "-Double Team",
        move4a : "-Payback",

        nameb : "Vileplume",
        levelb : "LV: 42",
        typeb : "Type: Grass/Poison",
        abilityb: "Ability: Chlorophyll",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Stun Spore",
        move2b : "-Acid",
        move3b : "-Petal Dance",
        move4b : "-Moonlight",

        namec : "Murkrow",
        levelc : "LV: 44",
        typec : "Type: Dark/Flying",
        abilityc: "Ability: Super Luck",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Feint Attack",
        move2c : "-Whirlwind",
        move3c : "-Pluck",
        move4c : "-Sucker Punch",

        named : "Gengar",
        leveld : "LV: 45",
        typed : "Type: Ghost/Poison",
        abilityd: "Ability: Levitate",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Lick",
        move2d : "-Spite",
        move3d : "-Destiny Bond",
        move4d : "-Focus Blast",

        namee : "Houndoom",
        levele : "LV: 47",
        typee : "Type: Dark/Fire",
        abilitye: "Ability: Flash Fire",
        iteme : "Item: Sitrus Berry",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Dark Pulse",
        move2e : "-Flamethrower",
        move3e : "-Crunch",
        move4e : "-Nasty Plot",
    },

    {
        namea : "Gyarados",
        levela : "LV: 46",
        typea : "Type: Water/Flying",
        abilitya: "Ability: Intimidate",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Waterfall",
        move2a : "-Dragon Pulse",
        move3a : "-Ice Fang",
        move4a : "-Flail",

        nameb : "Dragonite",
        levelb : "LV: 49",
        typeb : "Type: Dragon/Flying",
        abilityb: "Ability: Inner Focus",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Dragon Rush",
        move2b : "-Thunder Wave",
        move3b : "-Thunder",
        move4b : "-Hyper Beam",

        namec : "Dragonite",
        levelc : "LV: 49",
        typec : "Type: Dragon/Flying",
        abilityc: "Ability: Inner Focus",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Dragon Rush",
        move2c : "-Thunder Wave",
        move3c : "-Blizzard",
        move4c : "-Hyper Beam",

        named : "Aerodactyl",
        leveld : "LV: 48",
        typed : "Type: Rock/Flying",
        abilityd: "Ability: ",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Rock Slide",
        move2d : "-Aerial Ace",
        move3d : "-Crunch",
        move4d : "-Thunder Fang",

        namee : "Charizard",
        levele : "LV: 48",
        typee : "Type: Fire/Flying",
        abilitye: "Ability: ",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Air Slash",
        move2e : "-Fire Fang",
        move3e : "-Dragon Claw",
        move4e : "-Shadow Claw",

        namef : "Dragonite",
        levelf : "LV: 50",
        typef : "Type: Dragon/Flying",
        abilityf: "Ability: Inner Focus",
        itemf : "Item: Sitrus Berry",
        hpf : "HP: ",
        atkf : "Atk: ",
        deff : "Def: ",
        spatkf : "Sp. Atk: ",
        spdeff : "Sp. Def: ",
        spdf : "Spd: ",
        move1f : "-Outrage",
        move2f : "-Safeguard",
        move3f : "-Fire Blast",
        move4f : "-Hyper Beam",
    },

    {
        namea : "Graveler",
        levela : "LV: 51",
        typea : "Type: Rock/Ground",
        abilitya: "Ability: Sturdy",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Defense Curl",
        move2a : "-Rollout",
        move3a : "-Rock Slide",
        move4a : "-Earthquake",

        nameb : "Rhyhorn",
        levelb : "LV: 51",
        typeb : "Type: Ground/Rock",
        abilityb: "Ability: Rock Head",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Sandstorm",
        move2b : "-Scary Face",
        move3b : "-Earthquake",
        move4b : "-Horn Drill",

        namec : "Omastar",
        levelc : "LV: 53",
        typec : "Type: Rock/Water",
        abilityc: "Ability: Shell Armor",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Brine",
        move2c : "-Ancient Power",
        move3c : "-Spike Cannon",
        move4c : "-Protect",

        named : "Kabutops",
        leveld : "LV: 52",
        typed : "Type: Rock/Water",
        abilityd: "Ability: Battle Armor",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Rock Slide",
        move2d : "-Aqua Jet",
        move3d : "-Giga Drain",
        move4d : "-Endure",

        namee : "Onix",
        levele : "LV: 54",
        typee : "Type: Rock/Ground",
        abilitye: "Ability: Sturdy",
        iteme : "Item: Sitrus Berry",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Sandstorm",
        move2e : "-Rock Slide",
        move3e : "-Iron Tail",
        move4e : "-Screech",
    },

    {
        namea : "Golduck",
        levela : "LV: 49",
        typea : "Type: Water",
        abilitya: "Ability: Damp",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Water Pulse",
        move2a : "-Disable",
        move3a : "-Psych Up",
        move4a : "-Psychic",

        nameb : "Quagsire",
        levelb : "LV: 49",
        typeb : "Type: Water/Ground",
        abilityb: "Ability: Water Absorb",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Water Pulse",
        move2b : "-Amnesia",
        move3b : "-Earthquake",
        move4b : "-Rain Dance",

        namec : "Lapras",
        levelc : "LV: 52",
        typec : "Type: Water/Ice",
        abilityc: "Ability: Shell Armor",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Ice Beam",
        move2c : "-Sing",
        move3c : "-Water Pulse",
        move4c : "-Body Slam",

        named : "Starmie",
        leveld : "LV: 54",
        typed : "Type: Water/Psychic",
        abilityd: "Ability: Natural Cure",
        itemd : "Item: Sitrus Berry",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Water Pulse",
        move2d : "-Confuse Ray",
        move3d : "-Recover",
        move4d : "-Ice Beam",
    },

    {
        namea : "Raichu",
        levela : "LV: 51",
        typea : "Type: Electric",
        abilitya: "Ability: Static",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Thunder Wave",
        move2a : "-Quick Attack",
        move3a : "-Shock Wave",
        move4a : "-Double Team",

        nameb : "Electrode",
        levelb : "LV: 47",
        typeb : "Type: Electric",
        abilityb: "Ability: Static",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Thunder Wave",
        move2b : "-Double Team",
        move3b : "-Shock Wave",
        move4b : "-Light Screen",

        namec : "Electrode",
        levelc : "LV: 47",
        typec : "Type: Electric",
        abilityc: "Ability: Static",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Screech",
        move2c : "-Double Team",
        move3c : "-Self-Destruct",
        move4c : "-Charge Beam",

        named : "Magneton",
        leveld : "LV: 47",
        typed : "Type: Electric/Steel",
        abilityd: "Ability: Sturdy",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Supersonic",
        move2d : "-Double Team",
        move3d : "-Shock Wave",
        move4d : "-Mirror Shot",

        namee : "Electabuzz",
        levele : "LV: 53",
        typee : "Type: Electric",
        abilitye: "Ability: Static",
        iteme : "Item: Sitrus Berry",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Quick Attack",
        move2e : "-Shock Wave",
        move3e : "-Light Screen",
        move4e : "-Low Kick",
    },

    {
        namea : "Jumpluff",
        levela : "LV: 51",
        typea : "Type: Grass/Flying",
        abilitya: "Ability: Chlorophyll",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Leech Seed",
        move2a : "-U-Turn",
        move3a : "-Giga Drain",
        move4a : "-Sunny Day",

        nameb : "Tangela",
        levelb : "LV: 52",
        typeb : "Type: Grass",
        abilityb: "Ability: Chlorophyll",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Ancient Power",
        move2b : "-Wring Out",
        move3b : "-Sleep Powder",
        move4b : "-Giga Drain",

        namec : "Victreebel",
        levelc : "LV: 56",
        typec : "Type: Grass/Poison",
        abilityc: "Ability: Chlorophyll",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Sunny Day",
        move2c : "-Razor Leaf",
        move3c : "-Leaf Storm",
        move4c : "-Grass Knot",

        named : "Bellossom",
        leveld : "LV: 56",
        typed : "Type: Grass",
        abilityd: "Ability: Chlorophyll",
        itemd : "Item: Sitrus Berry",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Sunny Day",
        move2d : "-Solar Beam",
        move3d : "-Synthesis",
        move4d : "-Giga Drain",
    },

    {
        namea : "Crobat",
        levela : "LV: 47",
        typea : "Type: Poison/Flying",
        abilitya: "Ability: ",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Wing Attack",
        move2a : "-Confuse Ray",
        move3a : "-Supersonic",
        move4a : "-Screech",

        nameb : "Weezing",
        levelb : "LV: 44",
        typeb : "Type: Poison",
        abilityb: "Ability: ",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Sludge Bomb",
        move2b : "-Toxic",
        move3b : "-Explosion",
        move4b : "-Double Hit",

        namec : "Ariados",
        levelc : "LV: 47",
        typec : "Type: Bug/Poison",
        abilityc: "Ability: Insomnia",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Swagger",
        move2c : "-Night Shade",
        move3c : "-Poison Jab",
        move4c : "-Pin Missile",

        named : "Ariados",
        leveld : "LV: 47",
        typed : "Type: Bug/Poison",
        abilityd: "Ability: Insomnia",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Psychic",
        move2d : "-Poison Jab",
        move3d : "-Scary Face",
        move4d : "-Pin Missile",

        namee : "Venomoth",
        levele : "LV: 50",
        typee : "Type: Bug/Poison",
        abilitye: "Ability: ",
        iteme : "Item: Sitrus Berry",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Sludge Bomb",
        move2e : "-Double Team",
        move3e : "-Psychic",
        move4e : "-Signal Beam",
    },

    {
        namea : "Espeon",
        levela : "LV: 53",
        typea : "Type: Psychic",
        abilitya: "Ability: Synchronize",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Psychic",
        move2a : "-Calm Mind",
        move3a : "-Shadow Ball",
        move4a : "-Skill Swap",

        nameb : "Mr. Mime",
        levelb : "LV: 53",
        typeb : "Type: Psychic",
        abilityb: "Ability: Filter",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Psychic",
        move2b : "-Mimic",
        move3b : "-Light Screen",
        move4b : "-Skill Swap",

        namec : "Alakazam",
        levelc : "LV: 55",
        typec : "Type: Psychic",
        abilityc: "Ability: Inner Focus",
        itemc : "Item: Sitrus Berry",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Psychic",
        move2c : "-Reflect",
        move3c : "-Energy Ball",
        move4c : "-Skill Swap",
    },

    {
        namea : "Magcargo",
        levela : "LV: 54",
        typea : "Type: Fire/Rock",
        abilitya: "Ability: Flame Body",
        itema : "Item: White Herb",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Overheat",
        move2a : "-Sunny Day",
        move3a : "-Smog",
        move4a : "-Rock Slide",

        nameb : "Magmar",
        levelb : "LV: 54",
        typeb : "Type: Fire",
        abilityb: "Ability: Flame Body",
        itemb : "Item: White Herb",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Overheat",
        move2b : "-Confuse Ray",
        move3b : "-Thunder Punch",
        move4b : "-Sunny Day",

        namec : "Rapidash",
        levelc : "LV: 59",
        typec : "Type: Fire",
        abilityc: "Ability: Flash Fire",
        itemc : "Item: White Herb",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Overheat",
        move2c : "-Bounce",
        move3c : "-Flare Blitz",
        move4c : "-Quick Attack",
    },

    {
        namea : "Exeggutor",
        levela : "LV: 55",
        typea : "Type: Grass/Psychic",
        abilitya: "Ability: Chlorophyll",
        itema : "Item: None",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Leaf Storm",
        move2a : "-Hypnosis",
        move3a : "-Psychic",
        move4a : "-Trick Room",

        nameb : "Arcanine",
        levelb : "LV: 58",
        typeb : "Type: Fire",
        abilityb: "Ability: Intimidate",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Flare Blitz",
        move2b : "-Dragon Pulse",
        move3b : "-Extreme Speed",
        move4b : "-Roar",

        namec : "Rhydon",
        levelc : "LV: 58",
        typec : "Type: Ground/Rock",
        abilityc: "Ability: Rock Head",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Stone Edge",
        move2c : "-Earthquake",
        move3c : "-Thunder Fang",
        move4c : "-Megahorn",

        named : "Gyarados",
        leveld : "LV: 52",
        typed : "Type: Water/Flying",
        abilityd: "Ability: Intimidate",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Dragon Dance",
        move2d : "-Waterfall",
        move3d : "-Ice Fang",
        move4d : "-Return",

        namee : "Machamp",
        levele : "LV: 56",
        typee : "Type: Fighting",
        abilitye: "Ability: No Guard",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Dynamic Punch",
        move2e : "-Stone Edge",
        move3e : "-Earthquake",
        move4e : "-Thunder Punch",

        namef : "Pidgeot",
        levelf : "LV: 60",
        typef : "Type: Normal/Flying",
        abilityf: "Ability: Tangled Feet",
        itemf : "Item: Sitrus Berry",
        hpf : "HP: ",
        atkf : "Atk: ",
        deff : "Def: ",
        spatkf : "Sp. Atk: ",
        spdeff : "Sp. Def: ",
        spdf : "Spd: ",
        move1f : "-Return",
        move2f : "-Whirlwind",
        move3f : "-Air Slash",
        move4f : "-Mirror Move",
    },

    {
        namea : "Pikachu",
        levela : "LV: 88",
        typea : "Type: Electric",
        abilitya: "Ability: Static",
        itema : "Item: Light Ball",
        hpa : "HP: ",
        atka : "Atk: ",
        defa : "Def: ",
        spatka : "Sp. Atk: ",
        spdefa : "Sp. Def: ",
        spda : "Spd: ",
        move1a : "-Quick Attack",
        move2a : "-Thunderbolt",
        move3a : "-Iron Tail",
        move4a : "-Volt Tackle",

        nameb : "Lapras",
        levelb : "LV: 80",
        typeb : "Type: Water/Ice",
        abilityb: "Ability: Shell Armor",
        itemb : "Item: None",
        hpb : "HP: ",
        atkb : "Atk: ",
        defb : "Def: ",
        spatkb : "Sp. Atk: ",
        spdefb : "Sp. Def: ",
        spdb : "Spd: ",
        move1b : "-Psychic",
        move2b : "-Brine",
        move3b : "-Blizzard",
        move4b : "-Body Slam",

        namec : "Snorlax",
        levelc : "LV: 82",
        typec : "Type: Normal",
        abilityc: "Ability: Thick Fat",
        itemc : "Item: None",
        hpc : "HP: ",
        atkc : "Atk: ",
        defc : "Def: ",
        spatkc : "Sp. Atk: ",
        spdefc : "Sp. Def: ",
        spdc : "Spd: ",
        move1c : "-Giga Impact",
        move2c : "-Crunch",
        move3c : "-Blizzard",
        move4c : "-Shadow Ball",

        named : "Venusaur",
        leveld : "LV: 84",
        typed : "Type: Grass/Poison",
        abilityd: "Ability: Overgrow",
        itemd : "Item: None",
        hpd : "HP: ",
        atkd : "Atk: ",
        defd : "Def: ",
        spatkd : "Sp. Atk: ",
        spdefd : "Sp. Def: ",
        spdd : "Spd: ",
        move1d : "-Frenzy Plant",
        move2d : "-Giga Drain",
        move3d : "-Sludge Bomb",
        move4d : "-Sleep Powder",

        namee : "Charizard",
        levele : "LV: 84",
        typee : "Type: Fire/Flying",
        abilitye: "Ability: Blaze",
        iteme : "Item: None",
        hpe : "HP: ",
        atke : "Atk: ",
        defe : "Def: ",
        spatke : "Sp. Atk: ",
        spdefe : "Sp. Def: ",
        spde : "Spd: ",
        move1e : "-Blast Burn",
        move2e : "-Flare Blitz",
        move3e : "-Air Slash",
        move4e : "-Dragon Pulse",

        namef : "Blastoise",
        levelf : "LV: 84",
        typef : "Type: Water",
        abilityf: "Ability: Torrent",
        itemf : "Item: None",
        hpf : "HP: ",
        atkf : "Atk: ",
        deff : "Def: ",
        spatkf : "Sp. Atk: ",
        spdeff : "Sp. Def: ",
        spdf : "Spd: ",
        move1f : "-Hydro Cannon",
        move2f : "-Blizzard",
        move3f : "-Flash Cannon",
        move4f : "-Focus Blast",
    }
]

function displayHGSSTrainers() {

    let newTrainerId = this.id;
    if (newTrainerId !== currentTrainerId) {
        currentTrainerId = newTrainerId;
        showHGSSImages(newTrainerId);
        showPokemonHGSSImages(newTrainerId);
    }


    let hgssTrainer = this.dataset.member;

    document.querySelector('#name1').textContent = hgss_trainers [hgssTrainer].namea;
    document.querySelector('#level1').textContent = hgss_trainers [hgssTrainer].levela;
    document.querySelector('#type1').textContent = hgss_trainers [hgssTrainer].typea;
    document.querySelector('#ability1').textContent= hgss_trainers [hgssTrainer].abilitya;
    document.querySelector('#item1').textContent = hgss_trainers [hgssTrainer].itema;
    document.querySelector('#hp1').textContent = hgss_trainers [hgssTrainer].hpa;
    document.querySelector('#atk1').textContent = hgss_trainers [hgssTrainer].atka;
    document.querySelector('#def1').textContent = hgss_trainers [hgssTrainer].defa;
    document.querySelector('#spatk1').textContent = hgss_trainers [hgssTrainer].spatka;
    document.querySelector('#spdef1').textContent = hgss_trainers [hgssTrainer].spdefa;
    document.querySelector('#spd1').textContent = hgss_trainers [hgssTrainer].spda;
    document.querySelector('#move1_1').textContent = hgss_trainers [hgssTrainer].move1a;
    document.querySelector('#move2_1').textContent = hgss_trainers [hgssTrainer].move2a;
    document.querySelector('#move3_1').textContent = hgss_trainers [hgssTrainer].move3a;
    document.querySelector('#move4_1').textContent = hgss_trainers [hgssTrainer].move4a;

    
    document.querySelector('#name2').textContent = hgss_trainers [hgssTrainer].nameb;
    document.querySelector('#level2').textContent = hgss_trainers [hgssTrainer].levelb;
    document.querySelector('#type2').textContent = hgss_trainers [hgssTrainer].typeb;
    document.querySelector('#ability2').textContent= hgss_trainers [hgssTrainer].abilityb;
    document.querySelector('#item2').textContent = hgss_trainers [hgssTrainer].itemb;
    document.querySelector('#hp2').textContent = hgss_trainers [hgssTrainer].hpb;
    document.querySelector('#atk2').textContent = hgss_trainers [hgssTrainer].atkb;
    document.querySelector('#def2').textContent = hgss_trainers [hgssTrainer].defb;
    document.querySelector('#spatk2').textContent = hgss_trainers [hgssTrainer].spatkb;
    document.querySelector('#spdef2').textContent = hgss_trainers [hgssTrainer].spdefb;
    document.querySelector('#spd2').textContent = hgss_trainers [hgssTrainer].spdb;
    document.querySelector('#move1_2').textContent = hgss_trainers [hgssTrainer].move1b;
    document.querySelector('#move2_2').textContent = hgss_trainers [hgssTrainer].move2b;
    document.querySelector('#move3_2').textContent = hgss_trainers [hgssTrainer].move3b;
    document.querySelector('#move4_2').textContent = hgss_trainers [hgssTrainer].move4b;

    document.querySelector('#name3').textContent = hgss_trainers [hgssTrainer].namec;
    document.querySelector('#level3').textContent = hgss_trainers [hgssTrainer].levelc;
    document.querySelector('#type3').textContent = hgss_trainers [hgssTrainer].typec;
    document.querySelector('#ability3').textContent= hgss_trainers [hgssTrainer].abilityc;
    document.querySelector('#item3').textContent = hgss_trainers [hgssTrainer].itemc;
    document.querySelector('#hp3').textContent = hgss_trainers [hgssTrainer].hpc;
    document.querySelector('#atk3').textContent = hgss_trainers [hgssTrainer].atkc;
    document.querySelector('#def3').textContent = hgss_trainers [hgssTrainer].defc;
    document.querySelector('#spatk3').textContent = hgss_trainers [hgssTrainer].spatkc;
    document.querySelector('#spdef3').textContent = hgss_trainers [hgssTrainer].spdefc;
    document.querySelector('#spd3').textContent = hgss_trainers [hgssTrainer].spdc;
    document.querySelector('#move1_3').textContent = hgss_trainers [hgssTrainer].move1c;
    document.querySelector('#move2_3').textContent = hgss_trainers [hgssTrainer].move2c;
    document.querySelector('#move3_3').textContent = hgss_trainers [hgssTrainer].move3c;
    document.querySelector('#move4_3').textContent = hgss_trainers [hgssTrainer].move4c;

    document.querySelector('#name4').textContent = hgss_trainers [hgssTrainer].named;
    document.querySelector('#level4').textContent = hgss_trainers [hgssTrainer].leveld;
    document.querySelector('#type4').textContent = hgss_trainers [hgssTrainer].typed;
    document.querySelector('#ability4').textContent= hgss_trainers [hgssTrainer].abilityd;
    document.querySelector('#item4').textContent = hgss_trainers [hgssTrainer].itemd;
    document.querySelector('#hp4').textContent = hgss_trainers [hgssTrainer].hpd;
    document.querySelector('#atk4').textContent = hgss_trainers [hgssTrainer].atkd;
    document.querySelector('#def4').textContent = hgss_trainers [hgssTrainer].defd;
    document.querySelector('#spatk4').textContent = hgss_trainers [hgssTrainer].spatkd;
    document.querySelector('#spdef4').textContent = hgss_trainers [hgssTrainer].spdefd;
    document.querySelector('#spd4').textContent = hgss_trainers [hgssTrainer].spdd;
    document.querySelector('#move1_4').textContent = hgss_trainers [hgssTrainer].move1d;
    document.querySelector('#move2_4').textContent = hgss_trainers [hgssTrainer].move2d;
    document.querySelector('#move3_4').textContent = hgss_trainers [hgssTrainer].move3d;
    document.querySelector('#move4_4').textContent = hgss_trainers [hgssTrainer].move4d;

    document.querySelector('#name5').textContent = hgss_trainers [hgssTrainer].namee;
    document.querySelector('#level5').textContent = hgss_trainers [hgssTrainer].levele;
    document.querySelector('#type5').textContent = hgss_trainers [hgssTrainer].typee;
    document.querySelector('#ability5').textContent= hgss_trainers [hgssTrainer].abilitye;
    document.querySelector('#item5').textContent = hgss_trainers [hgssTrainer].iteme;
    document.querySelector('#hp5').textContent = hgss_trainers [hgssTrainer].hpe;
    document.querySelector('#atk5').textContent = hgss_trainers [hgssTrainer].atke;
    document.querySelector('#def5').textContent = hgss_trainers [hgssTrainer].defe;
    document.querySelector('#spatk5').textContent = hgss_trainers [hgssTrainer].spatke;
    document.querySelector('#spdef5').textContent = hgss_trainers [hgssTrainer].spdefe;
    document.querySelector('#spd5').textContent = hgss_trainers [hgssTrainer].spde;
    document.querySelector('#move1_5').textContent = hgss_trainers [hgssTrainer].move1e;
    document.querySelector('#move2_5').textContent = hgss_trainers [hgssTrainer].move2e;
    document.querySelector('#move3_5').textContent = hgss_trainers [hgssTrainer].move3e;
    document.querySelector('#move4_5').textContent = hgss_trainers [hgssTrainer].move4e;

    document.querySelector('#name6').textContent = hgss_trainers [hgssTrainer].namef;
    document.querySelector('#level6').textContent = hgss_trainers [hgssTrainer].levelf;
    document.querySelector('#type6').textContent = hgss_trainers [hgssTrainer].typef;
    document.querySelector('#ability6').textContent= hgss_trainers [hgssTrainer].abilityf;
    document.querySelector('#item6').textContent = hgss_trainers [hgssTrainer].itemf;
    document.querySelector('#hp6').textContent = hgss_trainers [hgssTrainer].hpf;
    document.querySelector('#atk6').textContent = hgss_trainers [hgssTrainer].atkf;
    document.querySelector('#def6').textContent = hgss_trainers [hgssTrainer].deff;
    document.querySelector('#spatk6').textContent = hgss_trainers [hgssTrainer].spatkf;
    document.querySelector('#spdef6').textContent = hgss_trainers [hgssTrainer].spdeff;
    document.querySelector('#spd6').textContent = hgss_trainers [hgssTrainer].spdf;
    document.querySelector('#move1_6').textContent = hgss_trainers [hgssTrainer].move1f;
    document.querySelector('#move2_6').textContent = hgss_trainers [hgssTrainer].move2f;
    document.querySelector('#move3_6').textContent = hgss_trainers [hgssTrainer].move3f;
    document.querySelector('#move4_6').textContent = hgss_trainers [hgssTrainer].move4f;
}

function showHGSSImages(trainerId) {
    var trainerPicture = document.querySelector("#trainer_image");
    
    trainerPicture.innerHTML = "";

    var imgTrainer = document.createElement("img");
    imgTrainer.src = "images/trainers/hgss/" + trainerId + ".png";
    trainerPicture.appendChild(imgTrainer);
}

function showPokemonHGSSImages(trainerId) {
    var pokemon1Picture = document.querySelector("#pokemon_1_image");
    var pokemon2Picture = document.querySelector("#pokemon_2_image");
    var pokemon3Picture = document.querySelector("#pokemon_3_image");
    var pokemon4Picture = document.querySelector("#pokemon_4_image");
    var pokemon5Picture = document.querySelector("#pokemon_5_image");
    var pokemon6Picture = document.querySelector("#pokemon_6_image");
    var imgPokemon1 = document.createElement("img");
    var imgPokemon2 = document.createElement("img");
    var imgPokemon3 = document.createElement("img");
    var imgPokemon4 = document.createElement("img");
    var imgPokemon5 = document.createElement("img");
    var imgPokemon6 = document.createElement("img");
    
    pokemon1Picture.innerHTML = "";
    pokemon2Picture.innerHTML = "";
    pokemon3Picture.innerHTML = "";
    pokemon4Picture.innerHTML = "";
    pokemon5Picture.innerHTML = "";
    pokemon6Picture.innerHTML = "";

    
    imgPokemon1.src = "images/pokemon/hgss/" + trainerId + "_1.png";
    imgPokemon2.src = "images/pokemon/hgss/" + trainerId + "_2.png";
    imgPokemon3.src = "images/pokemon/hgss/" + trainerId + "_3.png";
    imgPokemon4.src = "images/pokemon/hgss/" + trainerId + "_4.png";
    imgPokemon5.src = "images/pokemon/hgss/" + trainerId + "_5.png";
    imgPokemon6.src = "images/pokemon/hgss/" + trainerId + "_6.png";

    pokemon1Picture.appendChild(imgPokemon1);
    pokemon2Picture.appendChild(imgPokemon2);
    pokemon3Picture.appendChild(imgPokemon3);
    pokemon4Picture.appendChild(imgPokemon4);
    pokemon5Picture.appendChild(imgPokemon5);
    pokemon6Picture.appendChild(imgPokemon6);
}

falknerHGSS.addEventListener('click', displayHGSSTrainers);
bugsyHGSS.addEventListener('click', displayHGSSTrainers);
whitneyHGSS.addEventListener('click', displayHGSSTrainers);
mortyHGSS.addEventListener('click', displayHGSSTrainers);
chuckHGSS.addEventListener('click', displayHGSSTrainers);
jasmineHGSS.addEventListener('click', displayHGSSTrainers);
pryceHGSS.addEventListener('click', displayHGSSTrainers);
clairHGSS.addEventListener('click', displayHGSSTrainers);
willHGSS.addEventListener('click', displayHGSSTrainers);
kogaHGSS.addEventListener('click', displayHGSSTrainers);
brunoHGSS.addEventListener('click', displayHGSSTrainers);
karenHGSS.addEventListener('click', displayHGSSTrainers);
lanceHGSS.addEventListener('click', displayHGSSTrainers);
brockHGSS.addEventListener('click', displayHGSSTrainers);
mistyHGSS.addEventListener('click', displayHGSSTrainers);
ltsurgeHGSS.addEventListener('click', displayHGSSTrainers);
erikaHGSS.addEventListener('click', displayHGSSTrainers);
janineHGSS.addEventListener('click', displayHGSSTrainers);
sabrinaHGSS.addEventListener('click', displayHGSSTrainers);
blaineHGSS.addEventListener('click', displayHGSSTrainers);
blueHGSS.addEventListener('click', displayHGSSTrainers);
redHGSS.addEventListener('click', displayHGSSTrainers);